### PR TITLE
Create test scenario without pimcore

### LINKED ISSUE #8: tests failing: "[pimcore] Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: There is currently no session available. in RequestStack.php:126"
@blankse tests are failing completely the last few nights with 

> [pimcore] Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: There is currently no session available. in RequestStack.php:126"

Could you please take a look at this and get it sorted?

### PR DESCRIPTION
**Pull request by blankse**
Fix https://github.com/drud/ddev-pdfreactor/issues/8

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
This seems like a great approach, tests the actual intended functionality. The one thing I'd suggest adding is actually inspecting the pdf artifact that gets created, or at least make sure it gets created? Making sure it gets created and has some relevant content would be good. Maybe that's already there and I don't see it. 

Thanks for the fix!

**Comment by blankse** [comment]
@rfay I added a check for the return value. I don't know why the test failing now. In my local environment it works. Can you have a look?

**Comment by rfay** [comment]
I just restarted it and it completed successfully. I also couldn't tell by reading the output what had gone wrong.

You should know that you can ssh into the test though,  In https://github.com/drud/ddev-pdfreactor/actions/workflows/tests.yml, click "Run workflow", choose the branch of your PR (test_without_pimcore) and set debug_enabled=true, then it will activate tmate and you can manually interact with the whole environment.

**Review by rfay — APPROVED** [review]
Thanks for doing this. It looks right to me, anad now checks. Maybe it would be better if the check for valid output were directly in the test.bats instead of in the test.php, but I understand you had an environment to validate things with in the test.php.

Since we don't know why the test failed the first time, we can hope that it won't be flaky. IMO you can pull this when you think it's good. It's always good to create a new release after a pull, but since this is just tests it's not that relevant, but OK to do anyway.

Thanks!

**Comment by blankse** [comment]
> I just restarted it and it completed successfully. I also couldn't tell by reading the output what had gone wrong.
> 
> You should know that you can ssh into the test though, In https://github.com/drud/ddev-pdfreactor/actions/workflows/tests.yml, click "Run workflow", choose the branch of your PR (test_without_pimcore) and set debug_enabled=true, then it will activate tmate and you can manually interact with the whole environment.

Good to know, thx :)

I will merge this for now. If the error occurs again, I can debug it online.

**Pull request merged**
